{% set name = "openllm-core" %}
{% set version = "0.5.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/openllm_core-{{ version }}.tar.gz
  sha256: e48fa13e1172b859cba0288cdba23c90a6423e3a04d2b4e157221005b9a76308

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling ==1.18.0
    - hatch-vcs ==0.3.0
    - hatch-fancy-pypi-readme ==23.1.0
    - pip
  run:
    - python >={{ python_min }}
    - attrs >=23.2.0
    - pydantic >2
    #- cattrs >=23.1.0,<23.2.0
    - orjson
    - inflection
    - typing-extensions
    - mypy_extensions
    - packaging
    - deepmerge
# Import Failures
    #- packaging >=20.0 # openllm_core/utils/pkg.py", line 9,
    #- click-option-group # openllm_core/_configuration.py", line 13

test:
  imports:
    - openllm_core
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: 'OpenLLM Core: Core components for OpenLLM.'
  home: https://github.com/bentoml/OpenLLM
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - rxm7706
